common:
  read_more_buttons:
    - "button:has-text('Zobrazit více')"
    - "button:has-text('Číst dál')"
    - ".job-detail__description-button"
    - "text=Read more"
  intercept_noise:
    bad_patterns:
      - "google-analytics"
      - "hotjar"
      - "facebook"
      - "pixel"
      - "doubleclick"
      - "sentry"
      - "segment"
    resource_types:
      - "image"
      - "media"
      - "font"
      - "stylesheet" # Aggressively block styles for speed on WTTJ

scrapers:
  Jobs.cz:
    base_url: "https://www.jobs.cz/prace/?page="
    card: "article.SearchResultCard"
    title: "h2.SearchResultCard__title > a"
    company_selectors:
      - ".SearchResultCard__footerItem"
      - "[data-test='employer-name']"
      - "span.Tag--neutral"
    salary: "span.Tag--success"
    
  Prace.cz:
    base_url: "https://www.prace.cz/nabidky/?page="
    card: "li.search-result__advert"
    title: "a.link"
    company_selectors:
      - ".search-result__advert__box__item--company"
    salary: ".search-result__advert__box__item--salary"

  StartupJobs:
    base_url: "https://www.startupjobs.cz/nabidky"
    card: "a[href*='/nabidka/']" # Reverted to generic link selector (proven to work)
    title: "h2"
    company_selectors:
      - ".employer-name"
      - "span.text-gray-500" 
      - "div.flex.items-center span"
    salary_list_item: "li" # Reverted to generic list item

  WTTJ:
    base_url: "https://www.welcometothejungle.com/cs/jobs?aroundQuery=Czechia"
    card: "li" # Very generic to catch all list items
    title: "h4"
    link: "a[href*='/jobs/']" # More specific link to avoid company links
    company_selectors:
      - "span.sc-688y7f-0"
      - "header span" # Fallback

  Cocuma:
    base_url: "https://www.cocuma.cz/jobs/?page="
    card: "a.job-thumbnail" # Reverted to 'a' tag
    title: ".job-thumbnail-title"
    company: ".job-thumbnail-company"

  LinkedIn:
    base_url: "https://www.linkedin.com/jobs/search?keywords=&location=Czechia&f_TPR=r86400"
    card: "li"
    title: "h3"
    company: "h4"
    link: "a"
