common:
  read_more_buttons:
  - button:has-text('Zobrazit více')
  - button:has-text('Číst dál')
  - .job-detail__description-button
  - text=Read more
  - text=Show more
  - text=See more
  - button:has-text('View more')
  intercept_noise:
    bad_patterns:
    - google-analytics
    - hotjar
    - facebook
    - pixel
    - doubleclick
    - sentry
    - segment
    resource_types:
    - image
    - media
    - font
    - stylesheet
  fallback_cities:
  - praha
  - brno
  - ostrava
  - plzeň
  - liberec
  - olomouc
  - hradec králové
  - české budějovice
  - pardubice
  - zlín
  - havířov
  - kladno
  - most
  - opava
  - karviná
scrapers:
  Jobs.cz:
    base_url: https://www.jobs.cz/prace/?page=
    domain: https://www.jobs.cz
    card: article.SearchResultCard
    title: h2.SearchResultCard__title > a
    company_selectors:
    - '[data-test=''employer-name'']'
    - .SearchResultCard__companyName
    - .SearchResultCard__footerItem:nth-child(1)
    salary: span.Tag--success
    city_selectors:
    - .SearchResultCard__footerItem:has-text('Praha')
    - .SearchResultCard__footerItem:has-text('Brno')
    - .SearchResultCard__footerItem:has-text('Ostrava')
    - '[data-test=''location'']'
  Prace.cz:
    base_url: https://www.prace.cz/nabidky/?page=
    domain: https://www.prace.cz
    card: li.search-result__advert
    title: a.link
    company_selectors:
    - .search-result__advert__box__item--company
    salary: .search-result__advert__box__item--salary
    city_selectors:
    - .search-result__advert__box__item--location
    - .ico-map-marker + span
  StartupJobs:
    base_url: https://www.startupjobs.cz/nabidky
    domain: https://www.startupjobs.cz
    card: a[href*='/nabidka/']
    title: div.font-semibold
    company_selectors:
    - .employer-name
    - span.text-gray-500
    - div.flex.items-center span
    salary_list_item: li
    city_selectors:
    - .location
    - span:has-text('Praha')
    - span:has-text('Brno')
  WTTJ:
    base_url: https://www.welcometothejungle.com/cs/jobs?aroundQuery=Czechia
    domain: https://www.welcometothejungle.com
    card: li[data-testid="search-results-list-item-wrapper"]
    title: h2
    link: a[href*='/jobs/']
    company_selectors:
    - span.sc-688y7f-0
    - header span
    city_selectors:
    - '[data-testid=''job-location'']'
    - span:has-text('Prague')
  Cocuma:
    base_url: https://www.cocuma.cz/jobs/page/
    domain: https://www.cocuma.cz
    first_page_url: https://www.cocuma.cz/jobs/
    card: a.job-thumbnail
    title: .job-thumbnail-title
    company: .job-thumbnail-company
    city_selectors:
    - .job-thumbnail-location
    - span.location
  LinkedIn:
    base_url: https://www.linkedin.com/jobs/search?keywords=&location=Czechia&f_TPR=r86400
    domain: https://www.linkedin.com
    card: div.job-search-card
    title: h3.base-search-card__title
    company: h4.base-search-card__subtitle
    link: a.base-card__full-link
    city_selectors:
    - span.job-search-card__location
performance:
  scroll_delay_sec: 1.5
  rate_limit_min: 1.0
  rate_limit_max: 2.0
  scraper_delays:
    StartupJobs:
      scroll_delay: 1.8
    WTTJ:
      scroll_delay: 1.5
    LinkedIn:
      scroll_delay: 1.5
